general {
    lock_cmd = notify-send "Session locked"
}

listener {
    timeout = 300                                 # 5 минут бездействия
    on-timeout = brightnessctl set 10%            # Затемнить до 10%
    on-resume = brightnessctl set 80%             # МГНОВЕННО вернуть яркость на 80%
}

listener {
    timeout = 420                                 # 7 минут бездействия
    on-timeout = hyprctl dispatch dpms off        # Отключить экран
    on-resume = hyprctl dispatch dpms on          # Включить экран
}
